spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sesacc
    username: root
    password:
  data:
    redis:
      host: localhost
      port: 6397
  mail:
    host: smtp.gmail.com
  email:
    sender:
      name: SeSACC
      address: test@example.com

logging:
  level:
    org:
      springframework:
        security: TRACE

jwt-secret: developmentjwtkeydmdoiwj2398usd7ayf987124gugszdc9783287gf
origins: http://localhost:3000
